SELECT * FROM JAVASQL -- 드래그 후 알트 + x

CREATE TABLE JAVASQL1(
	TEST3 NVARCHAR2(10),
	TSET4 NVARCHAR2(10)
)

SELECT * FROM JAVASQL1

-- NAVER 테이블
-- 아이디, 비밀번호, 이름, 나이, 성별, 이메일, 연락처
-- 아이디를 PK로 지정하기.

DROP TABLE NAVER

CREATE TABLE NAVER(
	NID		    NVARCHAR2(10),
	NPW			NVARCHAR2(11),
	NNAME		NVARCHAR2(5),
	NAGE		NUMBER,
	NGENDER		NVARCHAR2(6),
	NEMAIL		NVARCHAR2(20),
	NPHONE		NVARCHAR2(13),
	
	CONSTRAINT NA_ID_PK PRIMARY KEY (NID)
)

SELECT * FROM NAVER


DROP TABLE DAUM

CREATE TABLE DAUM(
	DID		    NVARCHAR2(10),
	DPW			NVARCHAR2(11),
	DNAME		NVARCHAR2(5),
	DAGE		NUMBER,
	DGENDER		NVARCHAR2(6),
	DEMAIL		NVARCHAR2(20),
	DPHONE		NVARCHAR2(13),
	
	CONSTRAINT DA_ID_PK PRIMARY KEY (DID)
)

SELECT * FROM DAUM